apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: doan-staging
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.rabiloo.net/datnx-workshop/doan/backend:staging_f1d3fcec
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        - name: VNP_RETURN_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: VNP_RETURN_URL
        - name: OAUTH2_TARGET_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OAUTH2_TARGET_URL
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
      imagePullSecrets:
      - name: gitlab-registry

---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: doan-staging
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
